### ISSUE TITLE
Unable to decode HEIC.

### ISSUE THREAD

**Issue by jikac** [danbrakeley/heic2png#1]
I'm not going to pretend to know what's going on here, but I figured I would run this by you. I tried to convert one file and received this. Occurs in both PowerShell and Command Prompt.

```
PS [omitted] > heic2png -a
2024.03.22-14:54:38 [nfo] starting                      num_workers=1 version=v0.2.0 built_on=2022-02-13T23:20:48Z
2024.03.22-14:54:38 [ERR] conversion failed             heic_path=IMG_4595.HEIC png_path=IMG_4595.png error="unable to decode IMG_4595.HEIC: error reading \"ftyp\" box: got box type \"\\x00\\x14JF\" instead" worker_id=0
2024.03.22-14:54:38 [nfo] done                          num_errors=1
```

I'm willing to debug with you if it isn't an immediately obvious fix.

**Comment by danbrakeley** [comment]
Are you sure this file isn't corrupted?

heic2png uses [adrium/goheif](https://github.com/adrium/goheif) to do the actual heic decoding, so I didn't know much about heic file internals before now, but after looking at the goheif code, it looks like all heic files should have the bytes `0x66` ("f"), `0x74` ("t"), `0x79` ("y"), `0x70` ("p") near the top of the file, but the output you are seeing is telling you that your file has the bytes `0x0`, `0x12`, `0x4A` ("J"), `0x46` ("F"). Since those bytes weren't what was expected, the decoder doesn't know how to make sense of the rest of the file, and aborts.

**Comment by danbrakeley** [comment]
There is a newer version of goheif, so I can look into updating heic2png to use that, but I suspect that won't fix your issue.

**Comment by danbrakeley** [comment]
@jikaczmarski: Well, I've updated heic2png and published a [new release](https://github.com/danbrakeley/heic2png/releases). Let me know if that changes anything!

**Comment by danbrakeley** [comment]
@jikaczmarski I haven't heard anything, so I'm going to close this issue.
