### ISSUE TITLE
missing libraries

### ISSUE THREAD

**Issue by Doncellup** [danbrakeley/heic2png#3]
Hello,
I would like to use your program, but when I run the .exe on Windows, I get these two errors.
Can you please help me to resolve this?

![image](https://github.com/danbrakeley/heic2png/assets/90469321/bc6ae2c1-31f6-4779-9e4e-6f357cdf959c)
![image](https://github.com/danbrakeley/heic2png/assets/90469321/e0d26f40-c9d5-4cd9-b0d7-426e6769e374)

**Comment by danbrakeley** [comment]
Huh, there is something broken in the latest release. I've deleted it for now, and I'd suggest trying the [v0.2.0 release](https://github.com/danbrakeley/heic2png/releases/tag/v0.2.0) for now, while I look into what went wrong with v0.3.0.

**Comment by danbrakeley** [comment]
Well, I'm trying to figure out how to make a build that doesn't have those dependencies. I think I didn't notice because those .dll files come with Git for Windows, so I had them installed already. You could try installing Git for Windows, and meanwhile I'm trying to figure out how to statically link those deps via the github action I use to generate the release .exe.

**Comment by danbrakeley** [comment]
OK, instead of trying to statically link those dependencies, I found the .dll files themselves, and now copy them into the release zip as part of the build process.

So if you grab [release v0.3.11](https://github.com/danbrakeley/heic2png/releases/tag/v0.3.11), you should have all the needed .dll files in there, and it should run! If I missed a .dll, let me know, and I'll make sure it gets added.
